### ISSUE TITLE
How to load files inside the importer?

### ISSUE THREAD

**Issue by ShayanJavadi** [medialize/sass.js#90]
As you mentioned in #89 I checked out the importer, but it is unclear to me how to load the needed files inside of the method.

I have a lot of files inside my tree so explicitly adding each one to the preloader doens't make a lot of sense so here's what I have at the moment:
```
import sass from 'sass.js';

  const baseUrl = getBaseUrl();
  const scssURl = `${baseUrl}/scss/styles`;
  const directory = '';
  const scssfile = `styles.scss`;
  const files = [
    'styles.scss'
  ]
  sass.importer(function(request, done) {
    // how do I retrieve the missing files in here?
    // preloadFiles seems to be the only available method to load files
    // and it doesn't work in this case

    const file = [
      'variables.scss'
    ]
    sass.preloadFiles(scssURl, directory, file, done());
  });

  sass.preloadFiles(scssURl, directory, files, function callback() {
    sass.listFiles(function callback(list) {
      console.log(list);
    });

    sass.readFile(scssfile, function callback(content) {
      console.log(content);
      sass.compileFile(scssfile, function callback(result) =>{
        console.log(result);
      });
    });
  });
```

What do I need to do inside of the importer to get the missing files?

*** UPDATE ***

I came up with this:

```
  sass.importer(function(request, done) {
    const path = '/sass/';
    const url = `${scssURl}/${request.current}.scss`;
    const file = `${request.current}.scss`;
    if (request.path === null) {
      fetch(url)
        .then(response => response.text())
        .then(response => scssText = response)
        .then(() => {
          sass.writeFile(path.slice(sass._path.length) + file, scssText);
        })
        .then(() => {
          done({
            path: `${path}${file}`
          });
        });
    } else {
      done();
    }
  });
```

but now this causes an error after a few seconds of fetching files
here's the error:

```
Uncaught abort() at Error                                              sass.sync.js?216b:61 
    at jsStackTrace (eval at <anonymous> (http://localhost:3000/js/bundle.js:13633:2), <anonymous>:61:17533)
    at stackTrace (eval at <anonymous> (http://localhost:3000/js/bundle.js:13633:2), <anonymous>:61:17704)
    at Object.abort (eval at <anonymous> (http://localhost:3000/js/bundle.js:13633:2), <anonymous>:89:10683)
    at _abort (eval at <anonymous> (http://localhost:3000/js/bundle.js:13633:2), <anonymous>:61:436888)
    at Uf (eval at <anonymous> (http://localhost:3000/js/bundle.js:13633:2), <anonymous>:72:43403)
    at Zqa (eval at <anonymous> (http://localhost:3000/js/bundle.js:13633:2), <anonymous>:79:124932)
    at v9 (eval at <anonymous> (http://localhost:3000/js/bundle.js:13633:2), <anonymous>:79:83690)
    at Array.dg (eval at <anonymous> (http://localhost:3000/js/bundle.js:13633:2), <anonymous>:72:76069)
    at Object.Xga [as dynCall_vii] (eval at <anonymous> (http://localhost:3000/js/bundle.js:13633:2), <anonymous>:79:103564)
    at invoke_vii (eval at <anonymous> (http://localhost:3000/js/bundle.js:13633:2), <anonymous>:61:471591)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by rodneyrehm** [comment]
Looks like you're on the right track, but your importer may need a little tweaking. From what I can tell by just looking at the code this should work fine:

```js
sass.importer(function(request, done) {
  const url = `${scssURl}/${request.current}.scss`;
  const file = `${request.current}.scss`;

  if (request.path === null) {
    fetch(url)
      .then(response => response.text())
      .then(scssText => {
        sass.writeFile(file, scssText, function() {
          done({
            path: file
          });
        })
      }).catch(function(error) {
        console.error(error)
      })
  } else {
    done();
  }
});
```
